### ISSUE TITLE
Cache mega folder get links request

### ISSUE THREAD

**Issue by BakasuraRCE** [tonikelope/megacrypter#6]
When MegaCrypter starts the process of encrypting a Mega folder, it gets all the archives contained in it through an HTTP call to the MEGA API which has no cache and can be exhaustive when you have multiple subfolders and files in it.

In particular, this is the function that does not have a cache:

https://github.com/tonikelope/megacrypter/blob/5b8ed8ce6ce34da1760ae4b5cff5f4c279a93852/application/Utils/MegaApi.php#L286-L288

**Comment by tonikelope** [comment]
The structure of a folder is not cached because it can change (new files can be added for example) and in the following calls we would return an old version without realizing it.

The only thing MegaCrypter caches are the names of the files and their size (although there is a flag to ignore the cache when creating new links).

The MEGA API allows you to get, through a single API call, the complete structure of a folder and its subfolders and files. It is not necessary to make recursive calls.

Regards ;)
